- name: Nginxインストール
  yum: name=nginx state=latest
- name: Nginx起動
  service: name=nginx state=started enabled=yes

- name: Nginxの起動確認
  shell: ps aux | grep nginx
  register: ps_result
  changed_when: false
  
- name: nginx設定ファイルの設置
  template:
    src: ./templates/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: nginx本体の設定ファイルを変更
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Nginx再起動
  yum: name=nginx state=latest
- name: Nginx起動
  service: name=nginx state=restarted
  become: yes