## nginxインストール
- name: yum install nginx
  yum: name=nginx state=latest

## nginx起動
- name: systemctl start nginx
  service: name=nginx state=started enabled=yes

## プロセス確認
- name: ps aux | grep nginx
  shell: ps aux | grep nginx
  register: ps_result
  changed_when: false
  
## confファイルを設定
- name: set default.conf
  template:
    src: ./templates/default.conf
    dest: /etc/nginx/conf.d/default.conf

## nginx再起動
- name: systemctl restart nginx
  service: name=nginx state=restarted
  become: yes