## epeal-release追加
- name: yum install epel
  yum:
    name: epel-release
    state: installed

## remiリポジトリを追加
- name: yum install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: installed

## php関連のパッケージをインストール
- name: yum install php
  yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip
    - php73-php-pecl-mongodb

## php.iniをサーバーにコピー
- name: copy php.ini
  template:
    src: ./templates/php.ini
    dest: /etc/php.ini

## php-fpmの設定をコピー
- name: copy www.conf
  copy: src=./templates/www.conf dest=/etc/php-fpm.d/www.conf

## php-fpm再起動
- name: systemctl restart php-fpm
  service: name=php-fpm state=restarted
  become: yes

## php-fpm.sockファイルを作成
- name: copy php-fpm.sock
  copy: src=./templates/php-fpm.sock dest=/var/run/php-fpm/php-fpm.sock

## 所有者権限を変更
- name: chanch owner
  file:
    path: /var/run/php-fpm/php-fpm.sock
    owner: nginx
    group: nginx

## php-fpm再起動
- name: systemctl restart php-fpm
  service: name=php-fpm state=restarted
  become: yes

## composerをインストール
- name: install composer
  command: "{{ item }}"
  with_items:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - /usr/local/bin/composer global require laravel/installer

## ディレクトリを作成
- name: mkdir {{ list_of_directory }}
  file: 
    path: /var/www/html/"{{ item }}"
    state: directory
  with_items:
    -  "{{ list_of_directory[1] }}"
    -  "{{ list_of_directory[2] }}"
    -  "{{ list_of_directory[3] }}"
    -  "{{ list_of_directory[4] }}"
    -  "{{ list_of_directory[5] }}"

## laravelの新規プロジェクト作成
- name: create laravel-project
  shell: /usr/local/bin/composer create-project "laravel/laravel=5.6.*" web
  args:
    chdir: /var/www/html/dev
    creates: /var/www/html/"{{ item }}"/web
  with_items:
    -  "{{ list_of_directory[1] }}"
    -  "{{ list_of_directory[2] }}"
    -  "{{ list_of_directory[3] }}"
    -  "{{ list_of_directory[4] }}"
    -  "{{ list_of_directory[5] }}"

## ディレクトリの権限を変更
- name: change permission
  file:
    path: /var/www/html/{{ item }}
    state: directory
    mode: 0777
    recurse: yes
  with_items:
    -  "{{ list_of_directory[1] }}"
    -  "{{ list_of_directory[2] }}"
    -  "{{ list_of_directory[3] }}"
    -  "{{ list_of_directory[4] }}"
    -  "{{ list_of_directory[5] }}"