## epeal-release追加
- name: install epel
  yum:
    name: epel-release
    state: installed

## remiリポジトリを追加
- name: install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: installed

## php関連のパッケージをインストール
- name: install php
  yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip

## php.iniをサーバーにコピー
- template:
    src: ../template/php.ini
    dest: /etc/php.ini

## composerをインストール
- name: install composer
    command: "{{ item }}"
    with_items:
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
      - /usr/local/bin/composer global require laravel/installer