## epeal-release追加
- name: install epel
  yum:
    name: epel-release
    state: installed

## remiリポジトリを追加
- name: install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: installed

## php関連のパッケージをインストール
- name: install php
  yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip

## php.iniをサーバーにコピー
- template:
    src: ./templates/php.ini
    dest: /etc/php.ini

## php-fpmの設定をコピー
- name: php-fpm
  copy: src=./templates/www.conf dest=/etc/php-fpm.d/www.conf

## php-fpm起動
- name: php-fpm 再起動
  service: name=php-fpm state=restarted
  become: yes
## sockファイルを作成
- name: sock
  copy: src=./templates/php-fpm.sock dest=/var/run/php-fpm/php-fpm.sock

- file:
    path: /var/run/php-fpm/php-fpm.sock
    owner: nginx
    group: nginx

## php-fpm再起動
- name: php-fpm 再起動
  service: name=php-fpm state=restarted
  become: yes

## composerをインストール
- name: install composer
  command: "{{ item }}"
  with_items:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - /usr/local/bin/composer global require laravel/installer

- name: Laravel 5.6
  shell: composer global require "laravel/installer"
  args:
    creates: /root/.config/.composer/vendor/bin/laravel

- name: Laravel プロジェクト配置
  shell: composer create-project "laravel/laravel=5.6.*" testblog
  args:
    chdir: /var/www/html
    creates: /var/www/html/web